<?php
$data = array (
  0 => 
  array (
    'cat_id' => '153',
    'cat_name' => 'Baby Feeding',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '5',
    'sort_order' => '40',
    'has_children' => '2',
    'goods_num' => 0,
  ),
  1 => 
  array (
    'cat_id' => '154',
    'cat_name' => 'Perlengkapan Baby',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '4',
    'sort_order' => '41',
    'has_children' => '4',
    'goods_num' => 0,
  ),
  2 => 
  array (
    'cat_id' => '157',
    'cat_name' => 'Mama Product',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '43',
    'has_children' => '1',
    'goods_num' => 0,
  ),
  3 => 
  array (
    'cat_id' => '226',
    'cat_name' => 'Life Style',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '3',
    'sort_order' => '48',
    'has_children' => '4',
    'goods_num' => '2',
  ),
  4 => 
  array (
    'cat_id' => '207',
    'cat_name' => '中国食品/日用品',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '49',
    'has_children' => '4',
    'goods_num' => 0,
  ),
  5 => 
  array (
    'cat_id' => '155',
    'cat_name' => 'NB',
    'measure_unit' => '',
    'parent_id' => '152',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '1',
    'has_children' => '0',
    'goods_num' => '9',
  ),
  6 => 
  array (
    'cat_id' => '156',
    'cat_name' => 'S',
    'measure_unit' => '',
    'parent_id' => '152',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '2',
    'has_children' => '0',
    'goods_num' => '12',
  ),
  7 => 
  array (
    'cat_id' => '161',
    'cat_name' => 'M',
    'measure_unit' => '',
    'parent_id' => '152',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '3',
    'has_children' => '0',
    'goods_num' => 22,
  ),
  8 => 
  array (
    'cat_id' => '162',
    'cat_name' => 'L',
    'measure_unit' => '',
    'parent_id' => '152',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '4',
    'has_children' => '0',
    'goods_num' => 23,
  ),
  9 => 
  array (
    'cat_id' => '163',
    'cat_name' => 'XL',
    'measure_unit' => '',
    'parent_id' => '152',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '5',
    'has_children' => '0',
    'goods_num' => 16,
  ),
  10 => 
  array (
    'cat_id' => '164',
    'cat_name' => 'XXL',
    'measure_unit' => '',
    'parent_id' => '152',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '6',
    'has_children' => '0',
    'goods_num' => 14,
  ),
  11 => 
  array (
    'cat_id' => '181',
    'cat_name' => 'XXXL',
    'measure_unit' => '',
    'parent_id' => '152',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '7',
    'has_children' => '0',
    'goods_num' => '2',
  ),
  12 => 
  array (
    'cat_id' => '196',
    'cat_name' => 'Cream&Rash',
    'measure_unit' => '',
    'parent_id' => '152',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '8',
    'has_children' => '0',
    'goods_num' => '2',
  ),
  13 => 
  array (
    'cat_id' => '191',
    'cat_name' => 'Tissue',
    'measure_unit' => '',
    'parent_id' => '152',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '3',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '4',
  ),
  14 => 
  array (
    'cat_id' => '165',
    'cat_name' => 'Susu Bayi',
    'measure_unit' => '',
    'parent_id' => '153',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '38',
    'has_children' => '5',
    'goods_num' => 18,
  ),
  15 => 
  array (
    'cat_id' => '194',
    'cat_name' => 'Food',
    'measure_unit' => '',
    'parent_id' => '153',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '3',
    'goods_num' => 0,
  ),
  16 => 
  array (
    'cat_id' => '152',
    'cat_name' => 'Popok',
    'measure_unit' => '',
    'parent_id' => '154',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '48',
    'has_children' => '9',
    'goods_num' => 2,
  ),
  17 => 
  array (
    'cat_id' => '204',
    'cat_name' => 'Cleaning',
    'measure_unit' => '',
    'parent_id' => '154',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '3',
    'sort_order' => '50',
    'has_children' => '2',
    'goods_num' => 0,
  ),
  18 => 
  array (
    'cat_id' => '197',
    'cat_name' => 'Baby Bath',
    'measure_unit' => '',
    'parent_id' => '154',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '3',
    'goods_num' => 0,
  ),
  19 => 
  array (
    'cat_id' => '190',
    'cat_name' => 'Feeding Tool',
    'measure_unit' => '',
    'parent_id' => '154',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '3',
    'sort_order' => '50',
    'has_children' => '2',
    'goods_num' => 0,
  ),
  20 => 
  array (
    'cat_id' => '173',
    'cat_name' => 'Food',
    'measure_unit' => '',
    'parent_id' => '157',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '2',
    'goods_num' => 5,
  ),
  21 => 
  array (
    'cat_id' => '166',
    'cat_name' => '0-6 Bulan',
    'measure_unit' => '',
    'parent_id' => '165',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '1',
    'has_children' => '0',
    'goods_num' => 47,
  ),
  22 => 
  array (
    'cat_id' => '167',
    'cat_name' => '6-12 Bulan',
    'measure_unit' => '',
    'parent_id' => '165',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '2',
    'has_children' => '0',
    'goods_num' => 41,
  ),
  23 => 
  array (
    'cat_id' => '183',
    'cat_name' => 'Susu Anak',
    'measure_unit' => '',
    'parent_id' => '165',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '5',
    'has_children' => '0',
    'goods_num' => 139,
  ),
  24 => 
  array (
    'cat_id' => '145',
    'cat_name' => 'Khusus Alergi',
    'measure_unit' => '',
    'parent_id' => '165',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '3',
    'sort_order' => '7',
    'has_children' => '0',
    'goods_num' => 21,
  ),
  25 => 
  array (
    'cat_id' => '192',
    'cat_name' => 'PRE',
    'measure_unit' => '',
    'parent_id' => '165',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '3',
    'sort_order' => '8',
    'has_children' => '0',
    'goods_num' => '4',
  ),
  26 => 
  array (
    'cat_id' => '180',
    'cat_name' => 'Susu Ibu Hamil',
    'measure_unit' => '',
    'parent_id' => '173',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '6',
  ),
  27 => 
  array (
    'cat_id' => '186',
    'cat_name' => 'Lain',
    'measure_unit' => '',
    'parent_id' => '173',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '52',
    'has_children' => '0',
    'goods_num' => '6',
  ),
  28 => 
  array (
    'cat_id' => '189',
    'cat_name' => 'Lensa',
    'measure_unit' => '',
    'parent_id' => '174',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '5',
  ),
  29 => 
  array (
    'cat_id' => '176',
    'cat_name' => 'Perawatan Rambut',
    'measure_unit' => '',
    'parent_id' => '174',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '2',
  ),
  30 => 
  array (
    'cat_id' => '201',
    'cat_name' => 'Cups',
    'measure_unit' => '',
    'parent_id' => '190',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  31 => 
  array (
    'cat_id' => '200',
    'cat_name' => 'Bottle&Nipple',
    'measure_unit' => '',
    'parent_id' => '190',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  32 => 
  array (
    'cat_id' => '198',
    'cat_name' => 'Bubur',
    'measure_unit' => '',
    'parent_id' => '194',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '28',
  ),
  33 => 
  array (
    'cat_id' => '193',
    'cat_name' => 'Biskuit & Snack',
    'measure_unit' => '',
    'parent_id' => '194',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '3',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '9',
  ),
  34 => 
  array (
    'cat_id' => '195',
    'cat_name' => 'Cream',
    'measure_unit' => '',
    'parent_id' => '194',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '51',
    'has_children' => '0',
    'goods_num' => '1',
  ),
  35 => 
  array (
    'cat_id' => '202',
    'cat_name' => 'Shower',
    'measure_unit' => '',
    'parent_id' => '197',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '3',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
  ),
  36 => 
  array (
    'cat_id' => '199',
    'cat_name' => 'Baby Oil',
    'measure_unit' => '',
    'parent_id' => '197',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '3',
  ),
  37 => 
  array (
    'cat_id' => '203',
    'cat_name' => 'Lotion&Podwer',
    'measure_unit' => '',
    'parent_id' => '197',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '3',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  38 => 
  array (
    'cat_id' => '206',
    'cat_name' => 'Dishes',
    'measure_unit' => '',
    'parent_id' => '204',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '2',
  ),
  39 => 
  array (
    'cat_id' => '205',
    'cat_name' => 'Clothes',
    'measure_unit' => '',
    'parent_id' => '204',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '2',
  ),
  40 => 
  array (
    'cat_id' => '209',
    'cat_name' => '休闲零食',
    'measure_unit' => '',
    'parent_id' => '207',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '3',
    'sort_order' => '50',
    'has_children' => '4',
    'goods_num' => 0,
  ),
  41 => 
  array (
    'cat_id' => '210',
    'cat_name' => '烟酒茶',
    'measure_unit' => '',
    'parent_id' => '207',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '3',
    'sort_order' => '50',
    'has_children' => '5',
    'goods_num' => 0,
  ),
  42 => 
  array (
    'cat_id' => '211',
    'cat_name' => '洗护用品',
    'measure_unit' => '',
    'parent_id' => '207',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '3',
    'sort_order' => '50',
    'has_children' => '2',
    'goods_num' => '1',
  ),
  43 => 
  array (
    'cat_id' => '208',
    'cat_name' => '调料干货',
    'measure_unit' => '',
    'parent_id' => '207',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '3',
    'sort_order' => '50',
    'has_children' => '5',
    'goods_num' => 0,
  ),
  44 => 
  array (
    'cat_id' => '212',
    'cat_name' => '调味品',
    'measure_unit' => '',
    'parent_id' => '208',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '3',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '24',
  ),
  45 => 
  array (
    'cat_id' => '216',
    'cat_name' => '干货',
    'measure_unit' => '',
    'parent_id' => '208',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '3',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  46 => 
  array (
    'cat_id' => '213',
    'cat_name' => '方便速食',
    'measure_unit' => '',
    'parent_id' => '208',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '3',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  47 => 
  array (
    'cat_id' => '217',
    'cat_name' => '米/面/杂粮',
    'measure_unit' => '',
    'parent_id' => '208',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '3',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '2',
  ),
  48 => 
  array (
    'cat_id' => '214',
    'cat_name' => '肉类',
    'measure_unit' => '',
    'parent_id' => '208',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '7',
  ),
  49 => 
  array (
    'cat_id' => '215',
    'cat_name' => '肉类/豆类',
    'measure_unit' => '',
    'parent_id' => '209',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '3',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '10',
  ),
  50 => 
  array (
    'cat_id' => '219',
    'cat_name' => '果脯蜜饯',
    'measure_unit' => '',
    'parent_id' => '209',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '3',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
  ),
  51 => 
  array (
    'cat_id' => '220',
    'cat_name' => '糖果糕点',
    'measure_unit' => '',
    'parent_id' => '209',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '3',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '4',
  ),
  52 => 
  array (
    'cat_id' => '218',
    'cat_name' => '坚果炒货',
    'measure_unit' => '',
    'parent_id' => '209',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '3',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
  ),
  53 => 
  array (
    'cat_id' => '225',
    'cat_name' => '茶叶',
    'measure_unit' => '',
    'parent_id' => '210',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '3',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  54 => 
  array (
    'cat_id' => '222',
    'cat_name' => '芙蓉王',
    'measure_unit' => '',
    'parent_id' => '210',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  55 => 
  array (
    'cat_id' => '223',
    'cat_name' => '其他烟类',
    'measure_unit' => '',
    'parent_id' => '210',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '3',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '2',
  ),
  56 => 
  array (
    'cat_id' => '224',
    'cat_name' => '利群',
    'measure_unit' => '',
    'parent_id' => '210',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '3',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '2',
  ),
  57 => 
  array (
    'cat_id' => '221',
    'cat_name' => '好日子',
    'measure_unit' => '',
    'parent_id' => '210',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
  ),
  58 => 
  array (
    'cat_id' => '228',
    'cat_name' => '日用品',
    'measure_unit' => '',
    'parent_id' => '211',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  59 => 
  array (
    'cat_id' => '229',
    'cat_name' => '净水',
    'measure_unit' => '',
    'parent_id' => '211',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '2',
  ),
  60 => 
  array (
    'cat_id' => '177',
    'cat_name' => 'Mesin Mie',
    'measure_unit' => '',
    'parent_id' => '226',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
  ),
  61 => 
  array (
    'cat_id' => '174',
    'cat_name' => 'Kecantikan',
    'measure_unit' => '',
    'parent_id' => '226',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '2',
    'goods_num' => 0,
  ),
  62 => 
  array (
    'cat_id' => '227',
    'cat_name' => 'Electronical',
    'measure_unit' => '',
    'parent_id' => '226',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '14',
  ),
  63 => 
  array (
    'cat_id' => '179',
    'cat_name' => 'Water Purifier',
    'measure_unit' => '',
    'parent_id' => '226',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '2',
  ),
);
?>